version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./notes-backend
    container_name: notes-backend
    ports:
      - '5000:5000'
    env_file:
      - ./notes-backend/.env
    depends_on:
      - mongo
    volumes:
      - ./notes-backend:/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:80'
    depends_on:
      - backend


volumes:
  mongo-data: